PERSISTANCE: false
RESOURCES:
    STATIC_PIC_URI: "http://localhost:9090/pic"
    BANNERS_RELETIVE_PATH: "banners/"
    GOODS_RELETIVE_PATH: "goods/"
    AVARAE_RELETIVE_PATH: "avatar/"

HOST: "http://localhost"
PORT: 9090
SQLITE:
    DB_FILE: data/bookstore.db
